//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trivia.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trivia.UnitTests.GameData", typeof(GameData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 4
        ///Chet&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Question was incorrectly answered
        ///Chet was sent to the penalty box
        ///Pat is the current player
        ///They have rolled a 4
        ///Pat&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game00 {
            get {
                return ResourceManager.GetString("Game00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 3
        ///Pat&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 4
        ///Sue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game01 {
            get {
                return ResourceManager.GetString("Game01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 4
        ///Chet&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 1
        ///Pat&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 1
        ///Sue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game02 {
            get {
                return ResourceManager.GetString("Game02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 5
        ///Pat&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game03 {
            get {
                return ResourceManager.GetString("Game03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 5
        ///Chet&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 3
        ///Pat&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 1
        ///Su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game04 {
            get {
                return ResourceManager.GetString("Game04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 2
        ///Pat&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 3
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game05 {
            get {
                return ResourceManager.GetString("Game05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 5
        ///Chet&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 5
        ///Pat&apos;s new location is 5
        ///The category is Science
        ///Science Question 1
        ///Question was incorrectly answered
        ///Pat was sent to the penalty box
        ///Sue is the current player
        ///T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game06 {
            get {
                return ResourceManager.GetString("Game06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Question was incorrectly answered
        ///Chet was sent to the penalty box
        ///Pat is the current player
        ///They have rolled a 4
        ///Pat&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game07 {
            get {
                return ResourceManager.GetString("Game07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 5
        ///Chet&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 2
        ///Pat&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game08 {
            get {
                return ResourceManager.GetString("Game08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 3
        ///Chet&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 1
        ///Pat&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 2
        ///Su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game09 {
            get {
                return ResourceManager.GetString("Game09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 5
        ///Chet&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 4
        ///Pat&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 4
        ///Sue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game10 {
            get {
                return ResourceManager.GetString("Game10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 3
        ///Chet&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 3
        ///Pat&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 1
        ///Sue&apos;s ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game11 {
            get {
                return ResourceManager.GetString("Game11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 5
        ///Chet&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 1
        ///Pat&apos;s new location is 1
        ///The category is Science
        ///Science Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game12 {
            get {
                return ResourceManager.GetString("Game12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 3
        ///Chet&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 5
        ///Pat&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 1
        ///Su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game13 {
            get {
                return ResourceManager.GetString("Game13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 1
        ///Chet&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 3
        ///Pat&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 3
        ///Su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game14 {
            get {
                return ResourceManager.GetString("Game14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 3
        ///Chet&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 2
        ///Pat&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 5
        ///Sue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game15 {
            get {
                return ResourceManager.GetString("Game15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 1
        ///Chet&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 5
        ///Pat&apos;s new location is 5
        ///The category is Science
        ///Science Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game16 {
            get {
                return ResourceManager.GetString("Game16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 4
        ///Chet&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Question was incorrectly answered
        ///Chet was sent to the penalty box
        ///Pat is the current player
        ///They have rolled a 4
        ///Pat&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game17 {
            get {
                return ResourceManager.GetString("Game17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 1
        ///Chet&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 2
        ///Pat&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game18 {
            get {
                return ResourceManager.GetString("Game18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 4
        ///Chet&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 1
        ///Pat&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 4
        ///Sue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game19 {
            get {
                return ResourceManager.GetString("Game19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 1
        ///Chet&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 4
        ///Pat&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Question was incorrectly answered
        ///Pat was sent to the penalty box
        ///Sue is the current player
        ///They have [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game20 {
            get {
                return ResourceManager.GetString("Game20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 4
        ///Chet&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 3
        ///Pat&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 4
        ///Sue&apos;s new  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game21 {
            get {
                return ResourceManager.GetString("Game21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 1
        ///Pat&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game22 {
            get {
                return ResourceManager.GetString("Game22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 4
        ///Chet&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 5
        ///Pat&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 3
        ///Sue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game23 {
            get {
                return ResourceManager.GetString("Game23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Question was incorrectly answered
        ///Chet was sent to the penalty box
        ///Pat is the current player
        ///They have rolled a 3
        ///Pat&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game24 {
            get {
                return ResourceManager.GetString("Game24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 4
        ///Chet&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 2
        ///Pat&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 3
        ///Sue&apos;s  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game25 {
            get {
                return ResourceManager.GetString("Game25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 5
        ///Pat&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game26 {
            get {
                return ResourceManager.GetString("Game26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 5
        ///Chet&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 4
        ///Pat&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 2
        ///Sue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game27 {
            get {
                return ResourceManager.GetString("Game27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 2
        ///Pat&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 5
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game28 {
            get {
                return ResourceManager.GetString("Game28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 5
        ///Chet&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 1
        ///Pat&apos;s new location is 1
        ///The category is Science
        ///Science Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game29 {
            get {
                return ResourceManager.GetString("Game29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 4
        ///Pat&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 4
        ///Sue&apos;s  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game30 {
            get {
                return ResourceManager.GetString("Game30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 5
        ///Chet&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 3
        ///Pat&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 2
        ///Su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game31 {
            get {
                return ResourceManager.GetString("Game31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 3
        ///Chet&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 1
        ///Pat&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 4
        ///Su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game32 {
            get {
                return ResourceManager.GetString("Game32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 5
        ///Chet&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 5
        ///Pat&apos;s new location is 5
        ///The category is Science
        ///Science Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game33 {
            get {
                return ResourceManager.GetString("Game33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 3
        ///Chet&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Question was incorrectly answered
        ///Chet was sent to the penalty box
        ///Pat is the current player
        ///They have rolled a 3
        ///Pat&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 1
        ///Question was incorrectly answered
        ///Pat was sent to the penalty box
        ///Sue is the current play [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game34 {
            get {
                return ResourceManager.GetString("Game34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 1
        ///Chet&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 2
        ///Pat&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game35 {
            get {
                return ResourceManager.GetString("Game35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 3
        ///Chet&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 5
        ///Pat&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 3
        ///Su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game36 {
            get {
                return ResourceManager.GetString("Game36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 1
        ///Chet&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 4
        ///Pat&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 5
        ///Sue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game37 {
            get {
                return ResourceManager.GetString("Game37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 3
        ///Chet&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 2
        ///Pat&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 2
        ///Sue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game38 {
            get {
                return ResourceManager.GetString("Game38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 1
        ///Chet&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 1
        ///Pat&apos;s new location is 1
        ///The category is Science
        ///Science Question 1
        ///Question was incorrectly answered
        ///Pat was sent to the penalty box
        ///Sue is the current player
        ///T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game39 {
            get {
                return ResourceManager.GetString("Game39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 4
        ///Chet&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 4
        ///Pat&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 2
        ///Sue&apos;s new lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game40 {
            get {
                return ResourceManager.GetString("Game40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 1
        ///Chet&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Question was incorrectly answered
        ///Chet was sent to the penalty box
        ///Pat is the current player
        ///They have rolled a 3
        ///Pat&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They ha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game41 {
            get {
                return ResourceManager.GetString("Game41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 4
        ///Chet&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 1
        ///Pat&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 1
        ///Sue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game42 {
            get {
                return ResourceManager.GetString("Game42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 1
        ///Chet&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 5
        ///Pat&apos;s new location is 5
        ///The category is Science
        ///Science Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game43 {
            get {
                return ResourceManager.GetString("Game43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 4
        ///Chet&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 3
        ///Pat&apos;s new location is 3
        ///The category is Rock
        ///Rock Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 1
        ///Sue&apos;s new  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game44 {
            get {
                return ResourceManager.GetString("Game44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 2
        ///Pat&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 1
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 3
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game45 {
            get {
                return ResourceManager.GetString("Game45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 4
        ///Chet&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 5
        ///Pat&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 5
        ///Sue&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game46 {
            get {
                return ResourceManager.GetString("Game46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 4
        ///Pat&apos;s new location is 4
        ///The category is Pop
        ///Pop Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 3
        ///Sue&apos;s  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game47 {
            get {
                return ResourceManager.GetString("Game47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 5
        ///Chet&apos;s new location is 5
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 2
        ///Pat&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Question was incorrectly answered
        ///Pat was sent to the penalty box
        ///Sue is the current player
        ///The [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game48 {
            get {
                return ResourceManager.GetString("Game48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chet was added
        ///They are player number 1
        ///Pat was added
        ///They are player number 2
        ///Sue was added
        ///They are player number 3
        ///Chet is the current player
        ///They have rolled a 2
        ///Chet&apos;s new location is 2
        ///The category is Sports
        ///Sports Question 0
        ///Answer was corrent!!!!
        ///Chet now has 1 Gold Coins.
        ///Pat is the current player
        ///They have rolled a 1
        ///Pat&apos;s new location is 1
        ///The category is Science
        ///Science Question 0
        ///Answer was corrent!!!!
        ///Pat now has 1 Gold Coins.
        ///Sue is the current player
        ///They have rolled a 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game49 {
            get {
                return ResourceManager.GetString("Game49", resourceCulture);
            }
        }
    }
}
